baseURL = "https://0xgrit.github.io"
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = 'azazel'

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = true

[taxonomies]
tag = "tags"

[caches]
  [caches.images]
      dir = ':cacheDir/images'

disableKinds = ["taxonomoy", "term"]
